apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: wize-demo-django
  title: Demo django template
  description: Create a django project powered with python
  tags:
    - demo
    - django
    - python
spec:
  owner: web@example.com
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
      - repo_name
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      repo_name:
        title: Repository
        type: string
        description: Repo name of the component
      description:
        title: Description
        type: string
        description: Description of the component
